import type { Session, SessionEvent } from "@pet-pov/db";

/**
 * Seeded demo session for Goofinsmirtz's outdoor adventure.
 *
 * Events extracted from the actual catpov.mp4 footage:
 * Goofinsmirtz goes on an outdoor expedition — investigates a trampoline,
 * treks through dense bushes, gazes up at a large tree, finds a kibble bowl,
 * meets a tortoiseshell cat friend, then patrols a wooded area.
 *
 * When real Gemini extraction is ready, this module can be removed
 * and all data will come from Supabase instead.
 */

export const DEMO_SESSION_ID = "demo-biscuit-tuesday";

export const DEMO_SESSION: Session = {
  id: DEMO_SESSION_ID,
  owner_id: "demo-owner",
  pet_id: "demo-pet-goofinsmirtz",
  title: "Goofinsmirtz's Wild Tuesday",

  // ── Media references ─────────────────────────────────────────────────────
  video_url: "/demo/catpov.mp4",   // demo-local stand-in; production uses Cloudinary delivery URL
  cloudinary_public_id: "demo/catpov", // demo stand-in; production uses real Cloudinary public_id
  thumbnail_url: null,          // generated by Cloudinary on first load — not yet wired
  rendered_video_url: null,     // set after render pipeline completes
  audio_url: null,              // set after ElevenLabs TTS generation

  duration_seconds: 118, // ~2 minutes of footage
  status: "complete",
  modes_run: ["recap", "ask-my-pet"],
  created_at: "2026-03-25T09:00:00Z",
  updated_at: "2026-03-25T09:02:00Z",
};

/**
 * Session events extracted from the actual catpov.mp4 footage.
 * Goofinsmirtz is an outdoor explorer cat — this is a backyard/woodland adventure.
 *
 * TODO: Replace with real Gemini Vision extraction output.
 *       The shape is identical — swap getMockedSessionEvents()
 *       for a Supabase fetch and everything downstream works.
 */
export const DEMO_SESSION_EVENTS: SessionEvent[] = [
  {
    timestamp_start: 0,
    timestamp_end: 10,
    description: "Goofinsmirtz sniffs and investigates a blue trampoline in the garden, examining the frame and springs up close",
    subjects: ["cat", "trampoline", "garden"],
    actions: ["sniffing", "investigating", "circling"],
    emotion: "curious",
    environment: "backyard garden",
    confidence: 0.95,
  },
  {
    timestamp_start: 10,
    timestamp_end: 25,
    description: "Pushes through dense green bushes and tall grass on an adventurous jungle trek",
    subjects: ["cat", "bushes", "tall grass"],
    actions: ["walking", "pushing through foliage", "exploring"],
    emotion: "adventurous",
    environment: "backyard garden — dense vegetation",
    confidence: 0.93,
  },
  {
    timestamp_start: 25,
    timestamp_end: 35,
    description: "Walks up to the base of a massive tree and stares all the way up the trunk with intense focus",
    subjects: ["cat", "large tree"],
    actions: ["looking up", "observing", "sitting"],
    emotion: "focused",
    environment: "backyard — near large tree",
    confidence: 0.91,
  },
  {
    timestamp_start: 35,
    timestamp_end: 50,
    description: "Discovers a bowl of orange and brown kibble on the ground and settles in for a satisfying outdoor snack",
    subjects: ["cat", "kibble bowl", "food"],
    actions: ["eating", "sniffing food", "crunching"],
    emotion: "content",
    environment: "backyard — food station",
    confidence: 0.97,
  },
  {
    timestamp_start: 50,
    timestamp_end: 70,
    description: "Meets a tortoiseshell cat friend in the yard — they touch noses and stand close together in a friendly greeting",
    subjects: ["cat", "tortoiseshell cat", "friend"],
    actions: ["sniffing noses", "standing close", "social greeting"],
    emotion: "social",
    environment: "backyard",
    confidence: 0.96,
  },
  {
    timestamp_start: 70,
    timestamp_end: 118,
    description: "Embarks on a slow, deliberate patrol through a wooded area — crunching over dry leaves and pine needles between tall trees",
    subjects: ["cat", "woodland", "fallen leaves", "trees"],
    actions: ["walking", "patrolling", "sniffing ground"],
    emotion: "calm",
    environment: "wooded area",
    confidence: 0.94,
  },
];

/**
 * Returns mocked session events for the demo session.
 *
 * TODO: Replace this with a real Supabase fetch:
 *   const { data } = await db.from("session_events").select("events").eq("session_id", sessionId).single();
 *   return data?.events ?? [];
 */
export function getMockedSessionEvents(sessionId: string): SessionEvent[] | null {
  if (sessionId === DEMO_SESSION_ID) {
    return DEMO_SESSION_EVENTS;
  }
  return null;
}
